export { AboutMe } from './AboutMe/AboutMe'
export { Footer } from './Footer/Footer'
export { GetInTouch } from './GetInTouch/GetInTouch'
export { IntroHead } from './IntroHead/IntroHead'
export { Navbar } from './Navbar/Navbar'
export { NoteworthyProjects } from './NoteworthyProjects/NoteworthyProjects'
export { Section } from './Section/Section'
export { WorkExperience } from './WorkExperience/WorkExperience'
